// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR4tvCml63NiTkCjssjgJUMzb8EDvGKAs',
    appId: '1:770472432247:web:486903516a542af68fac72',
    messagingSenderId: '770472432247',
    projectId: 'fir-dd6df',
    authDomain: 'fir-dd6df.firebaseapp.com',
    storageBucket: 'fir-dd6df.firebasestorage.app',
    measurementId: 'G-85CEH0TKR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCODSqk10V6LT3F-XiRbC8JdontQ9oeFTY',
    appId: '1:770472432247:android:5a3ec1c993480da18fac72',
    messagingSenderId: '770472432247',
    projectId: 'fir-dd6df',
    storageBucket: 'fir-dd6df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuyXOkQ5qmVl6PIhwKPNYL-wcW5HuT2Wc',
    appId: '1:770472432247:ios:b87b944d98646f028fac72',
    messagingSenderId: '770472432247',
    projectId: 'fir-dd6df',
    storageBucket: 'fir-dd6df.firebasestorage.app',
    iosClientId:
        '770472432247-dtd95m1vlpmot9hjsulelruvm7i51fis.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuyXOkQ5qmVl6PIhwKPNYL-wcW5HuT2Wc',
    appId: '1:770472432247:ios:b87b944d98646f028fac72',
    messagingSenderId: '770472432247',
    projectId: 'fir-dd6df',
    storageBucket: 'fir-dd6df.firebasestorage.app',
    iosClientId:
        '770472432247-dtd95m1vlpmot9hjsulelruvm7i51fis.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR4tvCml63NiTkCjssjgJUMzb8EDvGKAs',
    appId: '1:770472432247:web:9ca53b6979878cd58fac72',
    messagingSenderId: '770472432247',
    projectId: 'fir-dd6df',
    authDomain: 'fir-dd6df.firebaseapp.com',
    storageBucket: 'fir-dd6df.firebasestorage.app',
    measurementId: 'G-F5HEKQSMLK',
  );
}
